#server:
#  port: 8087
#  servlet:
#    context-path: '/ead-course/'
#
spring:
  application:
    name: ead-course-service
  config:
    import: 'configserver:'
  cloud:
    config:
      dicovery:
        serviceId: ead-config-server
      username: configServerClient
      password: 'secretead123cs'
#  datasource:
#    url: jdbc:postgresql://localhost:5434/ead-course-v2
#    username: postgres
#    password: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
#    properties:
#      hibernate:
#        show-sql: true
#  rabbitmq:
#    addresses: amqps://pbnubozr:xM3lGCUyQzjF_kfiTtyGBRbHJgDa_W8N@jackal.rmq.cloudamqp.com/pbnubozr
#
#logging:
#  level:
#    com.ead: TRACE
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: INFO
#
#ead:
#  api:
#    url:
#      authuser: 'http://ead-authuser-service/ead-authuser'
#  broker:
#    exchange:
#      user-event-exchange: ead.userevent
#    queue:
#      user-event-queue:
#        name: ead.userevent.ms.course
#
#eureka:
#  client:
#    service-url:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost
